# Generated by Django 5.0.2 on 2024-02-25 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='count_product',
            field=models.IntegerField(default=1),
        ),
    ]
