# Generated by Django 5.0.2 on 2024-02-07 17:53

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file_path',
        ),
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=main.models.slugify_upload),
        ),
    ]
