# Generated by Django 5.0.2 on 2024-02-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_file_file_path_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='hash',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
