# Generated by Django 5.0.2 on 2024-02-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_file_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
