# Generated by Django 5.0.2 on 2024-02-08 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_file_product_delete_productimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.category'),
        ),
        migrations.AlterField(
            model_name='file',
            name='hash',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
