# Generated by Django 5.0.2 on 2024-02-12 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_productcolors_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
    ]
