# Generated by Django 5.0.2 on 2024-02-12 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_productcolors_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='category',
        ),
    ]
