# Generated by Django 5.0.2 on 2024-02-15 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_productsizes_product_remove_productsizes_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsizecolor',
            name='level',
        ),
        migrations.RemoveField(
            model_name='productsizecolor',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='productsizecolor',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='productsizecolor',
            name='tree_id',
        ),
        migrations.AlterField(
            model_name='productsizecolor',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.product'),
        ),
    ]
