# Generated by Django 5.0.2 on 2024-02-15 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_productsizecolor_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsizecolor',
            old_name='parent',
            new_name='product',
        ),
    ]
