# Generated by Django 5.0.2 on 2024-02-15 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_rename_parent_productsizecolor_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.file'),
        ),
    ]
