# Generated by Django 5.0.2 on 2024-02-20 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_file_uploaded_at'),
        ('main', '0017_category_count_product'),
    ]

    operations = [
    ]
