# Generated by Django 5.0.2 on 2024-02-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoping_cart',
            name='count_product',
            field=models.IntegerField(default=1),
        ),
    ]
